### PR TITLE
Release 1.2

### PR DESCRIPTION
**Pull request by rjhanes**
This release includes:

- Compatibility changes in code and in conda environment file for Python 3.10
- Conversion of all input datasets from CSV to XLSX with supporting code changes
- Input data validation checks that run automatically
- Documentation updates

See issues associated with the FY23 Q1 release milestone for additional details.

### CODE REVIEW

**Comment by rjhanes** [comment]
@tjlca This is the PR for our FY23 Q1 release. The review that's needed is:

- [ ] Spot check(s) on one or more analysis notebooks of your choice - could be what's in the codebase or one that you're working on locally - make sure everything runs normally and there are no warnings/errors
- [ ] Quick review of the updated documentation (clean version is located [here](https://nrel.github.io/tyche-docs/)) for any glaring errors (minor fixes & additions can be ongoing)

Note that I ran into a compatibility issue in creating Seaborn violin plots that (I think...) was due to a maplotlib/seaborn version conflict. To resolve, I updated the conda environment specs to use the most up-to-date versions of both matplotlib and seaborn. So specifically if the tutorial-basic analysis notebook isn't generating violin plots and is throwing an IndexError, that may be the issue.

I plan to merge this PR in by the end of the day Thursday, to include it in our Q1 deliverable

**Comment by tjlca** [comment]
@rjhanes Adding a note to the Readme that this is not compatible with new generation Macbook Arm64 processors.

**Comment by tjlca** [comment]
The violin plots worked for me without any issue.

**Comment by tjlca** [comment]
In the quick start guide, under section Setup Tyche environment using conda, we need to change the name of the yml file.

conda env create --file conda\win.yml

This should be changed to tyche.yml.

**Comment by tjlca** [comment]
Very minor edit. My apologies I should have caught it earlier. Some of the paragraph explanations for different datasets have a separate paragraph for Mandatory data. After the word Mandatory data there is a period. I think it will be better if the period is changed to a colon or a -.

**Comment by tjlca** [comment]
Table 3 Parameters dataset. The offset data type should be >=0 int.

**Comment by tjlca** [comment]
In the Deployment plan - Github Repository, should we write about the different releases or the current branches. There is no production branch now.

**Review by tapajyoti-ghosh — DISMISSED** [review]

**Comment by rjhanes** [comment]
- [ ] Remove deployment plan from docs (obsolete/to be heavily rewritten)
- [ ] Update YML file name in cheat sheet
- [ ] Offset data type in Parameters data dictionary (cheat sheet)

Re: The Mandatory data paragraphs - I updated this formatting to better fit with other, similar headings.

Re: The Arm64/M1 processor, there's nothing specific to the Tyche codebase or its prerequisites that's incompatible. The issue is rather with the Python installation as a whole. I've found fixes [here](https://towardsdatascience.com/how-to-easily-set-up-python-on-any-m1-mac-5ea885b73fab) and [here](https://www.anaconda.com/blog/apple-silicon-transition). There is also an M1-specific graphical installer available for [Anaconda](https://www.anaconda.com/products/distribution). I decided not to include discussion of this issue in the documentation because at this point I think it's safe to assume that any new users installing Tyche locally will either be installing Python for the first time (in which case, there's no issue provided they select the right distribution) or will already be using Python and will have already dealt with the M1 issue.

**Pull request merged**
