### PR TITLE
Issue 56: Add input data validation checks

### PR DESCRIPTION
**Pull request by rjhanes**
See Issue #56 for a complete list of the checks that were implemented by file. 

# Summary of Added Functionality

* Individual datasets (designs, results, etc) are now read in from a single XLSX file using the `DataManager` class with dataset-specific sub-classes. This enforces column names and data types in the input datasets.
* All of the checks implemented are run when either a `Designs` or `Investments` class is instantiated.
* If the input datasets have multiple errors, all of the errors are found at once and a list is printed out providing a summary of each failed check and identification of the input dataset that needs to change. (An alternative would be to have a single failed check terminate the validation process, but in the case that an input dataset needs many changes, the one-error-at-a-time approach would be tedious for the user.)
* There's also a check on the technology model (.py) file itself, first that it is importable and second that it contains the necessary methods as defined in the input data.
* Nothing downstream of the file I/O process has changed: the datasets look exactly as they did before and are used in the same way.

# Suggested Procedure for Testing and Review

Pull the latest commit from branch `issue-56`. Pick your favorite technology (I used pv-residential-simple for testing, so don't use that one) and test that the analysis notebook runs completely without errors. If the data validation checks are working properly, you should see no additional messages, warnings, or errors. 

Next, either introduce deliberate errors into that technology's dataset(s), or work with a dataset/technology that has known errors. See what, if any, checks fail when instantiating `Designs` or `Investments`. Are the resulting error messages what you expect? Do the error messages and other information provided make sense, and are they sufficiently informative?

Suggest any line-by-line changes as part of the PR review, or (for more complex changes or suspected bugs) as comments.

If you find that there are no necessary changes, mark this PR as approved and it'll be merged into `dev` shortly.

# Review Timeline 

Please try to complete your review by **Wednesday December 7** and let me know sooner rather than later if this won't be possible.

### CODE REVIEW

**Comment by tjlca** [comment]
Review 1: As the Designs.py and Type.py do not use the fixed type anywhere in the code, it was decided to drop that type from the indices table. I started out by testing the Simple_electrolysis code and it showed me a validation error - Unexpected type - {Fixed} That immediately helped me fix this issue. Good job!

**Comment by tjlca** [comment]
Review 2: I removed different mandatory types from the indices table and found that they were being properly caught by the data validation checker! 

Note - I ran a scenario where the data validation worked but there was inconsistencies in the technology model and the data provided.For example two input indices were required. I provided only one. These are not caught by the data validation check. But that is fine. These are modeling errors.

**Comment by tjlca** [comment]
Review 3: Focusing on the designs table - 

Removing input efficiency for water. 
**Data Validation:** Technology-Scenario combination ('Simple electrolysis', 'Base Electrolysis') has missing Variable Indexes. Check in designs.
{('Input efficiency', 'Water')}. 


Removing output efficiency for oxygen
Data Validation: Technology-Scenario combination ('Simple electrolysis', 'Base Electrolysis') has missing Variable Indexes. Check in designs.
{('Output efficiency', 'Oxygen')}



Note - something to add to the cheat sheet. Check below diagram. Even if scale does not an associated index, it actually is the catalyst. I guess both the life time and scale variable uses the capital index from the indices dataset which resolves this issue. 

image

All checks for design dataset passed successfully

**Comment by tjlca** [comment]
Review 4: Functions dataset

Data validation check does not catch the style = numpy missing data. Even if its not there, the model runs without any issues. 

Removing other functions are properly diagnosed by the data validation check.

**Comment by tjlca** [comment]
Review 5: Parameters dataset 

Randomly changed offset values and was captured by the data validation checker. 

Created duplicated offsets - Was captured by the data validation checker.

**Comment by tjlca** [comment]
Review 6 : Results dataset

1. Changed cost name to cost1. Captured by DV checker.
2. Mistyped index - Oxygen was written as oxy1. **Was not captured by the DVC.** But code ran fine. 
3. Deleted index oxygen. **Was not captured by the DVC.** But code ran fine. 
4. Deleted cost metric. **Was not captured by the DVC.**But code ran fine. 
5. Deleted a complete row in the results dataset. **Was not captured by the DVC.**But code ran fine.

**Comment by rjhanes** [comment]
Thank you @tjlca for the thorough review! I have one question, a couple notes/comments, and next steps (for me) at the bottom of this comment.

Question is - In Review 2, by "two input indices were required" do you mean that there were two Input Indexes in the designs dataset but only one in the indices dataset?

Notes/comments: 
* Re: Review 1, I completely forgot about the Type column in the indices dataset, but I'm leaning towards keeping it. The column is valuable for the user (person creating the dataset) and for enabling some of the cross-checks, even if it's not used directly by the analysis code. Plus, all the existing technology datasets still have it.
* Re: Review 3, my understanding is that the Scale is for the entire "system" (how that's defined varies from technology to technology), and so there will only ever be one. See for instance the tutorial-biorefinery model, which has 4 types of capital but still only one scale (the "biorefinery" scale, in that case).
* Re: Review 4, That numpy style thing is probably always going to be unused ... The original plan was to allow methods that can perform vector-based calculations with the numpy style or tensor-based calculations with the tensorflow style. At this point I'm not sure what that would even look like, much less how to implement it. I may just get rid of that column at some point.

Next steps:
I'm seeing the need for a few additional cross-checks, particularly in the results dataset, and will update the issue (#56) accordingly. I'll let you know when it's ready for another review.

**Comment by tjlca** [comment]
Question is - In Review 2, by "two input indices were required" do you mean that there were two Input Indexes in the designs dataset but only one in the indices dataset? 

This was actually a great question Rebecca. So here is the situation. The designs dataset has two inputs - Electricity and Water. The indices dataset thus has two input indices for water and electricity separately. Case 1:  I delete both of them, the DVC catches the error correctly - "No input indices". Case 2: I delete only water (which has the offset 0). DVC catches the error - " The offsets should start sequentially from 0". Case 3: I deleted only electricity (with offset 1). **This was not captured by the DVC**. It showed up as an issue when the technology model (py) file requested the entry for the second input and the array size mismatched resulting in modeling error.

**Comment by tjlca** [comment]
Review 7 - 

1. Made the tranches inconsistent between the tranches and the investment dataset. DVC indentified the error correctly. 

2. Deleted scenarios from the tranches scenario column. This was not captured by the DVC but did not affect the code. Code ran fine. 

3. Deleting tranches in investment data set is captured by the DVC. 

4. Deleting items from the Investment column, is **not captured by DVC** but does not affect the code also.

**Comment by tjlca** [comment]
Review on Bio refinery example: 

1. Missing entry in Designs dataset was identified successfully. 
2. Inconsistent function names in the technology model within the functions dataset was identified successfully. 
3. Missing Tranche in investment dataset captured. 
6. Results dataset issues are being captured by the DVC.

**Review by tjlca — APPROVED** [review]

**Pull request merged**
